# ============================================================
# zsh config
# ============================================================

# --- PATH ---------------------------------------------------
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
typeset -U path PATH fpath
path=("$HOME/.local/bin" $path)
path=("$HOME/.grok/bin" $path)
fpath=("$HOME/.grok/completions/zsh" $fpath)

# --- oh-my-zsh ----------------------------------------------
# custom/*.zsh 는 아래 source 시점에 자동 로드
# (macos-nfc, editor).
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=()
fpath=("$HOME/.zsh/plugins/zsh-completions/src" $fpath)
source "$ZSH/oh-my-zsh.sh"

# --- Environment --------------------------------------------
# EDITOR/VISUAL 은 custom/editor.zsh
export LANG="${LANG:-ko_KR.UTF-8}"
export PAGER="${PAGER:-less}"
export LESS="-R"

# --- History ------------------------------------------------
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY

# --- Options ------------------------------------------------
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt INTERACTIVE_COMMENTS
setopt NO_BEEP
setopt PROMPT_SUBST
setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END
setopt PATH_DIRS
setopt CORRECT
setopt EXTENDED_GLOB

# --- Completion ---------------------------------------------
# compinit 는 oh-my-zsh 가 이미 돌렸다.
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$HOME/.zsh/cache"
zstyle ':completion:*' complete-options true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

mkdir -p "$HOME/.zsh/cache"

# --- Aliases ------------------------------------------------
# ls/eza 한글 NFC 는 custom/macos-nfc.zsh 가 eza() 또는 ls 를 감싼다.
if (( $+commands[eza] )); then
  alias ls='eza --group-directories-first'
  alias ll='eza -lh --git --group-directories-first'
  alias la='eza -lha --git --group-directories-first'
  alias tree='eza --tree'
else
  alias ll='ls -lhG'
  alias la='ls -lahG'
  alias l='ls -G'
fi
if (( $+commands[bat] )); then
  alias cat='bat --paging=never --style=plain'
fi
alias grep='grep --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias work='cd ~/Documents'
alias reload='exec zsh'
alias devops='~/.tmux/smug-devops.sh'
alias path='echo -e ${PATH//:/\\n}'
alias ip='ipconfig getifaddr en0'
alias hidefiles='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
alias showfiles='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'

# --- Keybindings --------------------------------------------
bindkey -e

# Word movement with Option/Alt + arrows (iTerm2)
bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
# Word movement with Option + b/f (Meta)
bindkey '^[b' backward-word
bindkey '^[f' forward-word

# Delete word
bindkey '^[[3;3~' kill-word
bindkey '^[^?' backward-kill-word

# Home / End
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

# --- Plugins ------------------------------------------------
# 바이너리는 repo 에 안 넣는다. ~/.zsh/plugins 에 clone.
ZSH_PLUGIN_DIR="$HOME/.zsh/plugins"

if [[ -f "$ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  ZSH_AUTOSUGGEST_STRATEGY=(history completion)
  ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
  source "$ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

if [[ -f "$ZSH_PLUGIN_DIR/zsh-history-substring-search/zsh-history-substring-search.zsh" ]]; then
  source "$ZSH_PLUGIN_DIR/zsh-history-substring-search/zsh-history-substring-search.zsh"
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
  bindkey '^P' history-substring-search-up
  bindkey '^N' history-substring-search-down
fi

if (( $+commands[fzf] )); then
  if (( $+commands[rg] )); then
    export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  fi
  source <(fzf --zsh)
fi

if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh)"
fi

# Syntax highlighting MUST be sourced last
if [[ -f "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# 머신 로컬만: ~/.zshrc.local
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
